# -*- coding: utf-8 -*-
"""Updated.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19SzCp1MLtjOkZDJzDlWbOka4rVskWbnM
"""

import pandas as pd, numpy as np, re, string, os, joblib, time
import matplotlib.pyplot as plt, seaborn as sns
from wordcloud import WordCloud
from collections import Counter
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.model_selection import (train_test_split, cross_val_score,
                                     StratifiedKFold, GridSearchCV, learning_curve)
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import (accuracy_score, precision_score, recall_score, f1_score,
                             confusion_matrix, classification_report, roc_curve, auc,
                             ConfusionMatrixDisplay, roc_auc_score)
import warnings
warnings.filterwarnings('ignore')
plt.style.use('seaborn-v0_8')
sns.set_palette('husl')

import sys
sys.setrecursionlimit(2000)
pd.options.mode.chained_assignment = None

for resource in ['stopwords', 'wordnet', 'omw-1.4']:
    try: nltk.download(resource, quiet=True)
    except: pass

print('✅ All imports loaded successfully')

local_file = 'IMDB Dataset.csv'
drive_path = '/content/drive/MyDrive/Colab Notebooks/IMDB Dataset.csv'
df = None

print('🔍 Checking data sources...')

if os.path.exists(local_file):
    print(f'📂 Found locally: {local_file}')
    df = pd.read_csv(local_file, encoding='utf-8', engine='python', on_bad_lines='skip')
else:
    print('📂 Not found locally. Mounting Google Drive...')
    from google.colab import drive
    drive.mount('/content/drive')

    if os.path.exists(drive_path):
        print(f'📂 Found in Drive: {drive_path}')
        df = pd.read_csv(drive_path, encoding='utf-8', engine='python', on_bad_lines='skip')
    else:
        print('⏳ Auto-searching Drive...')
        import subprocess
        result = subprocess.run(
            ['find', '/content/drive', '-name', 'IMDB Dataset.csv', '-type', 'f'],
            capture_output=True, text=True)
        matches = [p for p in result.stdout.strip().split('\n') if p]
        if matches:
            drive_path = matches[0]
            print(f'✅ Found at: {drive_path}')
            df = pd.read_csv(drive_path, encoding='utf-8', engine='python', on_bad_lines='skip')
        else:
            print('❌ Dataset not found.')
            raise FileNotFoundError('IMDB Dataset.csv not found')

df = df.dropna(subset=['review']).reset_index(drop=True)
print(f'\n✅ Loaded: {len(df):,} reviews | Columns: {list(df.columns)}')
if len(df) < 45000:
    print('⚠️  WARNING: Dataset appears truncated (<45k rows).')
else:
    print(f'✅ Verified: Full dataset ({len(df):,} rows)')
print(f'\n📊 Class Distribution:\n{df["sentiment"].value_counts().to_string()}')
